<div style="text-align: center;">
    <img src="Hospital Management Analysis Project.png" alt="Description" style="display: block; margin: auto;">
</div>

# Hospital Management Analysis Project

## Project Overview
In this project, we conduct a comprehensive analytical study of **hospital operations and healthcare performance data** to uncover meaningful insights related to patient flow, resource utilization, treatment efficiency, and overall operational effectiveness.

## Objectives
By applying advanced data cleaning techniques, Exploratory Data Analysis (EDA), SQL-based data modeling, and Business Intelligence visualization tools, I aim to identify and measure key performance indicators (KPIs), including:

- Patient admission and discharge trends  
- Bed occupancy rates  
- Departmental efficiency  
- Average length of stay (ALOS)  
- Readmission patterns  
- Revenue and cost performance  

## Expected Outcomes
Through this analysis, I will generate data-driven insights that support strategic decision-making by:

- Optimizing hospital resource allocation  
- Improving operational workflow efficiency  
- Enhancing patient care quality  
- Reducing system bottlenecks  
- Strengthening overall healthcare management performance  

---

## Hospital Managment Dataset Description

- In This Part of the project, I will talk about some important columns and other stuff that need to be cleared before start.
- We have Total **5 CSV Filed** , And Total **39 Fields (Columns)** I will talk about Some of the columns that need some Explenations.
---

### Treatments.csv

#### Table Purpose
This table records medical treatments provided during patient appointments.

#### Columns Explanation

- **treatment_id**: Unique identifier for each treatment record.
- **appointment_id**: Foreign key linking the treatment to a specific appointment.
- **treatment_type**: Category or type of medical treatment provided.
- **description**: Detailed explanation of the treatment performed.
- **cost**: Financial cost associated with the treatment.
- **treatment_date**: Date when the treatment was administered.

---

### Appointments.csv

#### Table Purpose
This table tracks scheduled and completed appointments between patients and doctors.

#### Columns Explanation

- **appointment_id**: Unique identifier for each appointment.
- **patient_id**: Foreign key referencing the patient attending the appointment.
- **doctor_id**: Foreign key referencing the doctor assigned to the appointment.
- **appointment_date**: Scheduled date of the appointment.
- **appointment_time**: Scheduled time of the appointment.
- **reason_for_visit**: Stated reason or medical concern for the visit.
- **status**: Current status of the appointment (e.g., Completed, Cancelled, No-Show, Scheduled).

---

### Billing.csv

#### Table Purpose
This table stores financial transaction records related to patient treatments and billing operations.

#### Columns Explanation

- **bill_id**: Unique identifier for each billing transaction.
- **patient_id**: Foreign key referencing the patient associated with the bill.
- **treatment_id**: Foreign key linking the bill to a specific treatment provided.
- **bill_date**: Date when the bill was generated.
- **amount**: Total monetary value charged for the treatment (in hospital currency).
- **payment_method**: Method used for payment (e.g., Cash, Credit Card, Insurance).
- **payment_status**: Status of the payment (e.g., Paid, Pending, Cancelled).

---

### Doctors.csv

#### Table Purpose
This table contains detailed information about doctors working within the hospital system.

#### Columns Explanation

- **doctor_id**: Unique identifier for each doctor.
- **first_name**: Doctor’s first name.
- **last_name**: Doctor’s last name.
- **specialization**: Medical specialty (e.g., Cardiology, Neurology, Orthopedics).
- **phone_number**: Doctor’s contact number.
- **years_experience**: Total years of professional medical experience.
- **hospital_branch**: Branch or location where the doctor practices.
- **email**: Official email address of the doctor.

---

### Patients.csv

#### Table Purpose
This table stores demographic and registration information of hospital patients.

#### Columns Explanation

- **patient_id**: Unique identifier for each patient.
- **first_name**: Patient’s first name.
- **last_name**: Patient’s last name.
- **gender**: Patient’s gender.
- **date_of_birth**: Patient’s birth date (used to calculate age).
- **contact_number**: Patient’s primary phone number.
- **address**: Residential address of the patient.
- **registration_date**: Date when the patient was registered in the hospital system.
- **insurance_provider**: Name of the patient’s insurance company.
- **insurance_number**: Unique insurance policy number.
- **email**: Patient’s email address.

---

## Start of the Project

In [1]:
# Some Important Deploys before start

# The Main Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

#Libraries i will need
from wordcloud import WordCloud
import re
import os
import glob

#Librariea may i need
import random
import copy
import math

#Display options 
pd.options.display.max_columns = None
pd.options.display.max_rows = 20

### Data Wrangling

In [2]:
#Checking The Data and see how it looks and get some information about how it looks

# use glob to get all the csv files in the folder
path = os.getcwd()
csv_files = glob.glob(os.path.join("D:\Data Analysist\EraaSoft Data Analysis Diploma\Projects\Final Project (Graduation)\Database", "*.csv"))


# loop over the list of csv files
for f in csv_files:
    
    df = pd.read_csv(f)
    
    # print the location and filename
    print('Location:', f)
    print('File Name:', f.split("\\")[-1])
    
    # print the content
    print('Content:')
    display(df)
    print()

Location: D:\Data Analysist\EraaSoft Data Analysis Diploma\Projects\Final Project (Graduation)\Database\appointments.csv
File Name: appointments.csv
Content:

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,reason_for_visit,status
0,A001,P034,D009,2023-08-09,15:15:00,Therapy,Scheduled
1,A002,P032,D004,2023-06-09,14:30:00,Therapy,No-show
2,A003,P048,D004,2023-06-28,8:00:00,Consultation,Cancelled
3,A004,P025,D006,2023-09-01,9:15:00,Consultation,Cancelled
4,A005,P040,D003,2023-07-06,12:45:00,Emergency,No-show
...,...,...,...,...,...,...,...
195,A196,P045,D006,2023-10-26,9:45:00,Checkup,Cancelled
196,A197,P001,D005,2023-04-01,13:30:00,Emergency,No-show
197,A198,P022,D006,2023-05-15,8:30:00,Therapy,No-show
198,A199,P017,D001,2023-05-01,12:45:00,Follow-up,Completed
199,A200,P007,D005,2023-12-30,10:15:00,Consultation,Cancelled

Location: D:\Data Analysist\EraaSoft Data Analysis Diploma\Projects\Final Project (Graduation)\Database\billing.csv
File Name: billing.csv
Content:

,bill_id,patient_id,treatment_id,bill_date,amount,payment_method,payment_status
0,B001,P034,T001,2023-08-09,3941.97,Insurance,Pending
1,B002,P032,T002,2023-06-09,4158.44,Insurance,Paid
2,B003,P048,T003,2023-06-28,3731.55,Insurance,Paid
3,B004,P025,T004,2023-09-01,4799.86,Insurance,Failed
4,B005,P040,T005,2023-07-06,582.05,Credit Card,Pending
...,...,...,...,...,...,...,...
195,B196,P045,T196,2023-10-26,2477.80,Cash,Pending
196,B197,P001,T197,2023-04-01,975.49,Cash,Pending
197,B198,P022,T198,2023-05-15,3383.72,Cash,Failed
198,B199,P017,T199,2023-05-01,1472.17,Credit Card,Paid
199,B200,P007,T200,2023-12-30,3288.15,Insurance,Paid

Location: D:\Data Analysist\EraaSoft Data Analysis Diploma\Projects\Final Project (Graduation)\Database\doctors.csv
File Name: doctors.csv
Content:

,doctor_id,first_name,last_name,specialization,phone_number,years_experience,hospital_branch,email
0,D001,David,Taylor,Dermatology,8322010158,17,Westside Clinic,dr.david.taylor@hospital.com
1,D002,Jane,Davis,Pediatrics,9004382050,24,Eastside Clinic,dr.jane.davis@hospital.com
2,D003,Jane,Smith,Pediatrics,8737740598,19,Eastside Clinic,dr.jane.smith@hospital.com
3,D004,David,Jones,Pediatrics,6594221991,28,Central Hospital,dr.david.jones@hospital.com
4,D005,Sarah,Taylor,Dermatology,9118538547,26,Central Hospital,dr.sarah.taylor@hospital.com
5,D006,Alex,Davis,Pediatrics,6570137231,23,Central Hospital,dr.alex.davis@hospital.com
6,D007,Robert,Davis,Oncology,8217493115,26,Westside Clinic,dr.robert.davis@hospital.com
7,D008,Linda,Brown,Dermatology,9069162601,5,Westside Clinic,dr.linda.brown@hospital.com
8,D009,Sarah,Smith,Pediatrics,7387087517,26,Central Hospital,dr.sarah.smith@hospital.com
9,D010,Linda,Wilson,Oncology,6176383634,21,Eastside Clinic,dr.linda.wilson@hospital.com

Location: D:\Data Analysist\EraaSoft Data Analysis Diploma\Projects\Final Project (Graduation)\Database\patients.csv
File Name: patients.csv
Content:

,patient_id,first_name,last_name,gender,date_of_birth,contact_number,address,registration_date,insurance_provider,insurance_number,email
0,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,WellnessCorp,INS840674,david.williams@mail.com
1,P002,Emily,Smith,F,1984-10-12,8228188767,321 Maple Dr,2022-01-15,PulseSecure,INS354079,emily.smith@mail.com
2,P003,Laura,Jones,M,1977-08-21,8397029847,321 Maple Dr,2022-02-07,PulseSecure,INS650929,laura.jones@mail.com
3,P004,Michael,Johnson,F,1981-02-20,9019443432,123 Elm St,2021-03-02,HealthIndia,INS789944,michael.johnson@mail.com
4,P005,David,Wilson,M,1960-06-23,7734463155,123 Elm St,2021-09-29,MedCare Plus,INS788105,david.wilson@mail.com
...,...,...,...,...,...,...,...,...,...,...,...
45,P046,Michael,Taylor,F,1986-09-01,8019925828,456 Oak Ave,2021-07-31,MedCare Plus,INS368799,michael.taylor@mail.com
46,P047,Jane,Moore,M,1995-12-13,8715732851,321 Maple Dr,2022-05-20,WellnessCorp,INS337549,jane.moore@mail.com
47,P048,Emily,Miller,M,1983-03-24,8720989381,123 Elm St,2023-06-19,PulseSecure,INS694319,emily.miller@mail.com
48,P049,David,Moore,M,1972-11-26,7712937941,321 Maple Dr,2023-06-14,MedCare Plus,INS584299,david.moore@mail.com
49,P050,Laura,Wilson,M,1993-12-27,8301134730,321 Maple Dr,2023-04-28,WellnessCorp,INS712210,laura.wilson@mail.com

Location: D:\Data Analysist\EraaSoft Data Analysis Diploma\Projects\Final Project (Graduation)\Database\treatments.csv
File Name: treatments.csv
Content:

,treatment_id,appointment_id,treatment_type,description,cost,treatment_date
0,T001,A001,Chemotherapy,Basic screening,3941.97,2023-08-09
1,T002,A002,MRI,Advanced protocol,4158.44,2023-06-09
2,T003,A003,MRI,Standard procedure,3731.55,2023-06-28
3,T004,A004,MRI,Basic screening,4799.86,2023-09-01
4,T005,A005,ECG,Standard procedure,582.05,2023-07-06
...,...,...,...,...,...,...
195,T196,A196,Chemotherapy,Advanced protocol,2477.80,2023-10-26
196,T197,A197,Physiotherapy,Standard procedure,975.49,2023-04-01
197,T198,A198,ECG,Basic screening,3383.72,2023-05-15
198,T199,A199,Chemotherapy,Basic screening,1472.17,2023-05-01
199,T200,A200,X-Ray,Basic screening,3288.15,2023-12-30

In [3]:
#Checking The Shape in all the data

# use glob to get all the csv files in the folder
path = os.getcwd()
csv_files = glob.glob(os.path.join("D:\Data Analysist\EraaSoft Data Analysis Diploma\Projects\Final Project (Graduation)\Database", "*.csv"))


# loop over the list of csv files
for f in csv_files:
    
    df = pd.read_csv(f)
    
    #check for Shape of the Data Frames
    SHAPE = df.shape
    
    # print the filename
    print('Shape of:', f.split("\\")[-1])
    
    # print the Shape
    display(SHAPE)
    print()

Shape of: appointments.csv

(200, 7)

Shape of: billing.csv

(200, 7)

Shape of: doctors.csv

(10, 8)

Shape of: patients.csv

(50, 11)

Shape of: treatments.csv

(200, 6)

In [4]:
#Getting Info about all the data

# use glob to get all the csv files in the folder
path = os.getcwd()
csv_files = glob.glob(os.path.join("D:\Data Analysist\EraaSoft Data Analysis Diploma\Projects\Final Project (Graduation)\Database", "*.csv"))


# loop over the list of csv files
for f in csv_files:
    
    df = pd.read_csv(f)
    
    #check for any Null values in the Data Frames
    Info = df.info()
    
    # print the filename
    print('Info of:', f.split("\\")[-1])
    
    # print the Info
    display(Info)
    print()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   appointment_id    200 non-null    object
 1   patient_id        200 non-null    object
 2   doctor_id         200 non-null    object
 3   appointment_date  200 non-null    object
 4   appointment_time  200 non-null    object
 5   reason_for_visit  200 non-null    object
 6   status            200 non-null    object
dtypes: object(7)
memory usage: 11.1+ KB
Info of: appointments.csv

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   bill_id         200 non-null    object
 1   patient_id      200 non-null    object
 2   treatment_id    200 non-null    object
 3   bill_date       200 non-null    object
 4   amount          200 non-null    float64
 5   payment_method  200 non-null    object
 6   payment_status  200 non-null    object
dtypes: float64(1), object(6)
memory usage: 11.1+ KB
Info of: billing.csv

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   doctor_id         10 non-null     object
 1   first_name        10 non-null     object
 2   last_name         10 non-null     object
 3   specialization    10 non-null     object
 4   phone_number      10 non-null     int64
 5   years_experience  10 non-null     int64
 6   hospital_branch   10 non-null     object
 7   email             10 non-null     object
dtypes: int64(2), object(6)
memory usage: 772.0+ bytes
Info of: doctors.csv

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          50 non-null     object
 1   first_name          50 non-null     object
 2   last_name           50 non-null     object
 3   gender              50 non-null     object
 4   date_of_birth       50 non-null     object
 5   contact_number      50 non-null     int64
 6   address             50 non-null     object
 7   registration_date   50 non-null     object
 8   insurance_provider  50 non-null     object
 9   insurance_number    50 non-null     object
 10  email               50 non-null     object
dtypes: int64(1), object(10)
memory usage: 4.4+ KB
Info of: patients.csv

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   treatment_id    200 non-null    object
 1   appointment_id  200 non-null    object
 2   treatment_type  200 non-null    object
 3   description     200 non-null    object
 4   cost            200 non-null    float64
 5   treatment_date  200 non-null    object
dtypes: float64(1), object(5)
memory usage: 9.5+ KB
Info of: treatments.csv

None

In [5]:
#Checking For Duplicates in all the data

# use glob to get all the csv files in the folder
path = os.getcwd()
csv_files = glob.glob(os.path.join("D:\Data Analysist\EraaSoft Data Analysis Diploma\Projects\Final Project (Graduation)\Database", "*.csv"))


# loop over the list of csv files
for f in csv_files:
    
    df = pd.read_csv(f)
    
    #check for any duplicated values in the Data Frames
    duplicate = df.duplicated().any()
    
    # print the filename
    print('File Name:', f.split("\\")[-1])
    
    # print the Duplicates
    print('Does the DataFrame have any duplicate?:')

    # if displayed (False) ==> No Duplicates , if displayed (True) ==> Duplicates
    display(duplicate)
    print()

File Name: appointments.csv
Does the DataFrame have any duplicate?:

np.False_

File Name: billing.csv
Does the DataFrame have any duplicate?:

np.False_

File Name: doctors.csv
Does the DataFrame have any duplicate?:

np.False_

File Name: patients.csv
Does the DataFrame have any duplicate?:

np.False_

File Name: treatments.csv
Does the DataFrame have any duplicate?:

np.False_

In [6]:
#Another Check For Null Values in all the data

# use glob to get all the csv files in the folder
path = os.getcwd()
csv_files = glob.glob(os.path.join("D:\Data Analysist\EraaSoft Data Analysis Diploma\Projects\Final Project (Graduation)\Database", "*.csv"))


# loop over the list of csv files
for f in csv_files:
    
    df = pd.read_csv(f)
    
    #check for any Null values in the Data Frames
    Nulls = df.isnull().any().any()
    
    # print the filename
    print('File Name:', f.split("\\")[-1])
    
    # print the Nulls
    print('Does the DataFrame have any Nulls?:')

    # if displayed (False) ==> No Null Values , if displayed (True) ==> Null Values
    display(Nulls)
    print()

File Name: appointments.csv
Does the DataFrame have any Nulls?:

np.False_

File Name: billing.csv
Does the DataFrame have any Nulls?:

np.False_

File Name: doctors.csv
Does the DataFrame have any Nulls?:

np.False_

File Name: patients.csv
Does the DataFrame have any Nulls?:

np.False_

File Name: treatments.csv
Does the DataFrame have any Nulls?:

np.False_

In [7]:
#Before we head to the Next Step the Date Columns data type need to be changed

folder_path = 'D:\Data Analysist\EraaSoft Data Analysis Diploma\Projects\Final Project (Graduation)\Database'
column_names = ['appointment_date','bill_date','date_of_birth','registration_date','treatment_date']

# Use glob to find all CSV files in the specified folder
csv_files = glob.glob(os.path.join(folder_path, "*.csv"))

# Loop over all CSV files
for file in csv_files:
    print(f"Processing file: {file}")
    
    try:
        # Read CSV file
        df = pd.read_csv(file)
        
        # Loop through each column in the list
        for col in column_names:
            if col in df.columns:
                print(f"  Converting column: {col}")
                df[col] = pd.to_datetime(df[col], errors='coerce')
                
            else:
                print(f"  Column not found: {col}")

        # Save the modified DataFrame back to the same file
        df.to_csv(file, index=False)
        print(f"Successfully updated and saved: {file}\n")
        
    except Exception as e:
        print(f"Error processing file {file}: {e}\n")

print("All files processed.")

Processing file: D:\Data Analysist\EraaSoft Data Analysis Diploma\Projects\Final Project (Graduation)\Database\appointments.csv
  Converting column: appointment_date
  Column not found: bill_date
  Column not found: date_of_birth
  Column not found: registration_date
  Column not found: treatment_date
Successfully updated and saved: D:\Data Analysist\EraaSoft Data Analysis Diploma\Projects\Final Project (Graduation)\Database\appointments.csv

Processing file: D:\Data Analysist\EraaSoft Data Analysis Diploma\Projects\Final Project (Graduation)\Database\billing.csv
  Column not found: appointment_date
  Converting column: bill_date
  Column not found: date_of_birth
  Column not found: registration_date
  Column not found: treatment_date
Successfully updated and saved: D:\Data Analysist\EraaSoft Data Analysis Diploma\Projects\Final Project (Graduation)\Database\billing.csv

Processing file: D:\Data Analysist\EraaSoft Data Analysis Diploma\Projects\Final Project (Graduation)\Database\doctors.csv
  Column not found: appointment_date
  Column not found: bill_date
  Column not found: date_of_birth
  Column not found: registration_date
  Column not found: treatment_date
Successfully updated and saved: D:\Data Analysist\EraaSoft Data Analysis Diploma\Projects\Final Project (Graduation)\Database\doctors.csv

Processing file: D:\Data Analysist\EraaSoft Data Analysis Diploma\Projects\Final Project (Graduation)\Database\patients.csv
  Column not found: appointment_date
  Column not found: bill_date
  Converting column: date_of_birth
  Converting column: registration_date
  Column not found: treatment_date
Successfully updated and saved: D:\Data Analysist\EraaSoft Data Analysis Diploma\Projects\Final Project (Graduation)\Database\patients.csv

Processing file: D:\Data Analysist\EraaSoft Data Analysis Diploma\Projects\Final Project (Graduation)\Database\treatments.csv
  Column not found: appointment_date
  Column not found: bill_date
  Column not found: date_of_birth
  Column not found: registration_date
  Converting column: treatment_date
Successfully updated and saved: D:\Data Analysist\EraaSoft Data Analysis Diploma\Projects\Final Project (Graduation)\Database\treatments.csv

All files processed.

#### Summary After Checking the Data
1. The Data is Clean there is no Missing Values or duplicates.
2. The Columns Data Types is correct for this kind of data

>The **`Data Frames`** is ready for the next step

**The Next Setp will be Transfrom the Dataframes To a Cleaned CSV Files and apply it to a database Using SQL Server Managment Tool**

In [8]:
# Define The Target folder
folder_path = r"D:\Data Analysist\EraaSoft Data Analysis Diploma\Projects\Final Project (Graduation)\Database"

# Get all CSV files inside the folder
csv_files = glob.glob(os.path.join(folder_path, "*.csv"))


# New folder for cleaned files
cleaned_folder = os.path.join(folder_path, "Cleaned Version")
# Create cleaned folder if it does not exist
os.makedirs(cleaned_folder, exist_ok=True)


for file_path in csv_files:
    df = pd.read_csv(file_path)
    
    # Extract filename without extension
    file_name = os.path.splitext(os.path.basename(file_path))[0]    
    # Create new cleaned file name
    cleaned_file_name = f"{file_name}_Cleaned.csv" 
   
    # Full Cleaned path
    cleaned_path = os.path.join(cleaned_folder, cleaned_file_name)
    
    # Export DataFrame again as CSV
    df.to_csv(cleaned_path, index=False)
    
    # Print info
    print(f"Original File: {file_name}.csv")
    print(f"Saved Cleaned File: {cleaned_file_name}")
    print("-" * 50)

Original File: appointments.csv
Saved Cleaned File: appointments_Cleaned.csv
--------------------------------------------------
Original File: billing.csv
Saved Cleaned File: billing_Cleaned.csv
--------------------------------------------------
Original File: doctors.csv
Saved Cleaned File: doctors_Cleaned.csv
--------------------------------------------------
Original File: patients.csv
Saved Cleaned File: patients_Cleaned.csv
--------------------------------------------------
Original File: treatments.csv
Saved Cleaned File: treatments_Cleaned.csv
--------------------------------------------------

---------------

# End Of The Notebook